wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.30
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: similar to resnet
batchsize:
  desc: null
  value: 128
dataset_id:
  desc: null
  value: shape dataset
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
